# Kiernan Nicholls
# Code to write and read files from 01_input_scrape.R
library(tidyverse)

## write_csv(members_115,        "./input/members_115.csv")
## write_csv(members_116,        "./input/members_116.csv")
## write_csv(model_district,     "./input/model_district.csv")
## write_csv(model_house,        "./input/model_house.csv")
## write_csv(model_seat,         "./input/model_seat.csv")
## write_csv(model_senate,       "./input/model_senate.csv")
## write_csv(election_results,   "./input/election_results.csv")
## write_csv(lean_district,      "./input/lean_district.csv")
## write_csv(lean_states,        "./input/lean_states.csv")
## write_csv(polls_generic,      "./input/polls_generic.csv")
## write_csv(polls_house,        "./input/polls_house.csv")
## write_csv(polls_senate,        "./input/polls_senate.csv")

market_data      <- read_csv("./input/market_data.csv")
members_115      <- read_csv("./input/members_115.csv")
members_116      <- read_csv("./input/members_116.csv")
model_district   <- read_csv("./input/model_district.csv")
model_house      <- read_csv("./input/model_house.csv")
model_seat       <- read_csv("./input/model_seat.csv")
model_senate     <- read_csv("./input/model_senate.csv")
election_results <- read_csv("./input/election_results.csv")
lean_district    <- read_csv("./input/lean_district.csv")
lean_states      <- read_csv("./input/lean_states.csv")
polls_generic    <- read_csv("./input/polls_generic.csv")
polls_house      <- read_csv("./input/polls_house.csv")
polls_senate     <- read_csv("./input/polls_senate.csv")
